// @flow

import type { Cocktail } from './Types';

export const cocktails: $ReadOnlyArray<Cocktail> = [
  {
    name: 'Coffee',
    ingredients: [],
    strength: 0,
    signature: false,
    nonalcoholic: true,
  },
  {
    name: 'Tea',
    ingredients: [],
    strength: 0,
    signature: false,
    nonalcoholic: true,
  },
  {
    name: 'Hot Tang',
    ingredients: [],
    strength: 0,
    signature: false,
    nonalcoholic: true,
  },
  {
    name: 'Hot Cocoa',
    ingredients: [],
    strength: 0,
    signature: false,
    nonalcoholic: true,
  },
  {
    name: 'Coca-Cola',
    ingredients: [],
    strength: 0,
    signature: false,
    nonalcoholic: true,
  },
  {
    name: 'Fever-tree Elderflower Tonic',
    ingredients: [],
    strength: 0,
    signature: false,
    nonalcoholic: true,
  },
  {
    name: 'Fever-tree Blood Orange Soda',
    ingredients: [],
    strength: 0,
    signature: false,
    nonalcoholic: true,
  },
  {
    name: 'Negroni',
    ingredients: ['gin', 'sweet vermouth', 'campari'],
    strength: 3,
    signature: true,
    nonalcoholic: false,
  },
  {
    name: 'Queen Elizabeth',
    ingredients: ['rum', 'lime', 'grenadine'],
    strength: 3,
    signature: true,
    nonalcoholic: false,
  },
  {
    name: 'Long Island Iced Tea',
    ingredients: [
      'gin',
      'tequila',
      'vodka',
      'rum',
      'Cointreau',
      'simple syrup',
      'lemon',
      'cola',
    ],
    strength: 3,
    signature: true,
    nonalcoholic: false,
  },
  {
    name: 'Bacardi Cocktail - Ritz version',
    ingredients: ['rum', 'dry vermouth', 'lemon', 'simple syrup', 'grenadine'],
    strength: 2,
    signature: true,
    nonalcoholic: false,
  },
  {
    name: 'Ward Eight',
    ingredients: ['whiskey', 'simple syrup', 'lemon', 'grenadine'],
    strength: 2,
    signature: true,
    nonalcoholic: false,
  },
  {
    name: 'Mark Twain Cocktail',
    ingredients: ['whiskey', 'lemon', 'simple syrup', 'angostura bitters'],
    strength: 2,
    signature: true,
    nonalcoholic: false,
  },
  {
    name: 'Whiskey sour',
    ingredients: ['whiskey', 'lemon', 'simple syrup'],
    strength: 2,
    signature: true,
    nonalcoholic: false,
  },
  {
    name: 'The LJ 75',
    ingredients: ['gin', 'champagne', 'lemon', 'elderflower liqueur'],
    strength: 2,
    signature: true,
    nonalcoholic: false,
  },
  {
    name: 'Gin Daisy',
    ingredients: ['gin', 'lemon', 'grenadine', 'simple syrup', 'club soda'],
    strength: 2,
    signature: true,
    nonalcoholic: false,
  },
  {
    name: 'Boulevard',
    ingredients: ['whiskey', 'Cointreau', 'dry vermouth'],
    strength: 3,
    signature: false,
    nonalcoholic: false,
  },
  {
    name: 'Rob Roy',
    ingredients: ['whiskey', 'sweet vermouth', 'angostura bitters'],
    strength: 3,
    signature: false,
    nonalcoholic: false,
  },
  {
    name: 'Old Pal',
    ingredients: ['whiskey', 'dry vermouth', 'campari'],
    strength: 3,
    signature: false,
    nonalcoholic: false,
  },
  {
    name: 'Boulevardier',
    ingredients: ['whiskey', 'sweet vermouth', 'campari'],
    strength: 3,
    signature: false,
    nonalcoholic: false,
  },
  {
    name: 'Manhattan',
    ingredients: ['whiskey', 'sweet vermouth', 'angostura bitters'],
    strength: 3,
    signature: false,
    nonalcoholic: false,
  },
  {
    name: 'El Presidente',
    ingredients: ['rum', 'dry vermouth', 'Cointreau', 'grenadine'],
    strength: 3,
    signature: false,
    nonalcoholic: false,
  },
  {
    name: 'Bacardi Cocktail',
    ingredients: ['rum', 'lime', 'grenadine'],
    strength: 3,
    signature: false,
    nonalcoholic: false,
  },
  {
    name: 'Kamikaze',
    ingredients: ['vodka', 'Cointreau', 'lime'],
    strength: 3,
    signature: false,
    nonalcoholic: false,
  },
  {
    name: 'Black Russian',
    ingredients: ['vodka', 'coffee liqueur'],
    strength: 3,
    signature: false,
    nonalcoholic: false,
  },
  {
    name: "Devil's Torch",
    ingredients: ['vodka', 'dry vermouth', 'grenadine'],
    strength: 3,
    signature: false,
    nonalcoholic: false,
  },
  {
    name: 'Mudslide Shot',
    ingredients: ['vodka', 'Irish cream liqueur', 'coffee liqueur'],
    strength: 3,
    signature: false,
    nonalcoholic: false,
  },
  {
    name: 'Gin and It',
    ingredients: ['gin', 'sweet vermouth', 'angostura bitters'],
    strength: 3,
    signature: false,
    nonalcoholic: false,
  },
  {
    name: 'The Vampire',
    ingredients: ['gin', 'dry vermouth', 'lime'],
    strength: 3,
    signature: false,
    nonalcoholic: false,
  },
  {
    name: 'White Lady',
    ingredients: ['gin', 'Cointreau', 'lemon'],
    strength: 3,
    signature: false,
    nonalcoholic: false,
  },
  {
    name: 'Gin Sour',
    ingredients: ['gin', 'lemon', 'simple syrup'],
    strength: 3,
    signature: false,
    nonalcoholic: false,
  },
  {
    name: 'Royal Romance',
    ingredients: ['gin', 'Cointreau', 'grenadine'],
    strength: 3,
    signature: false,
    nonalcoholic: false,
  },
  {
    name: 'Upside-down martini',
    ingredients: ['dry vermouth', 'gin'],
    strength: 3,
    signature: false,
    nonalcoholic: false,
  },
  {
    name: "Devil's Own",
    ingredients: ['gin', 'dry vermouth', 'Cointreau', 'angostura bitters'],
    strength: 3,
    signature: false,
    nonalcoholic: false,
  },
  {
    name: 'Gibson',
    ingredients: ['gin', 'dry vermouth'],
    strength: 3,
    signature: false,
    nonalcoholic: false,
  },
  {
    name: 'Margarita',
    ingredients: ['tequila', 'Cointreau', 'lime'],
    strength: 3,
    signature: false,
    nonalcoholic: false,
  },
  {
    name: 'Mexican Firing squad',
    ingredients: ['tequila', 'lime', 'grenadine', 'angostura bitters'],
    strength: 3,
    signature: false,
    nonalcoholic: false,
  },
  {
    name: 'B52',
    ingredients: ['Cointreau', 'coffee liqueur', 'Irish cream liqueur'],
    strength: 3,
    signature: false,
    nonalcoholic: false,
  },
  {
    name: 'Gimlet',
    ingredients: ['gin', 'lime', 'simple syrup'],
    strength: 2,
    signature: false,
    nonalcoholic: false,
  },
  {
    name: 'Fitzgerald',
    ingredients: ['gin', 'lemon', 'simple syrup', 'angostura bitters'],
    strength: 2,
    signature: false,
    nonalcoholic: false,
  },
  {
    name: 'Gin Rickey',
    ingredients: ['gin', 'lime', 'simple syrup', 'club soda'],
    strength: 2,
    signature: false,
    nonalcoholic: false,
  },
  {
    name: 'Bitter French',
    ingredients: ['gin', 'campari', 'lemon', 'simple syrup', 'champagne'],
    strength: 2,
    signature: false,
    nonalcoholic: false,
  },
  {
    name: 'French 75',
    ingredients: ['gin', 'champagne', 'lemon', 'simple syrup'],
    strength: 2,
    signature: false,
    nonalcoholic: false,
  },
  {
    name: 'American Flyer',
    ingredients: ['champagne', 'rum', 'lime', 'sugar'],
    strength: 2,
    signature: false,
    nonalcoholic: false,
  },
  {
    name: 'Daiquiri',
    ingredients: ['rum', 'lime', 'simple syrup'],
    strength: 2,
    signature: false,
    nonalcoholic: false,
  },
  {
    name: 'Tipperary',
    ingredients: ['whiskey', 'sweet vermouth'],
    strength: 2,
    signature: false,
    nonalcoholic: false,
  },
  {
    name: 'Americano',
    ingredients: ['campari', 'sweet vermouth', 'club soda'],
    strength: 2,
    signature: false,
    nonalcoholic: false,
  },
  {
    name: 'Addington Cocktail',
    ingredients: ['dry vermouth', 'sweet vermouth', 'club soda'],
    strength: 2,
    signature: false,
    nonalcoholic: false,
  },
  {
    name: 'Cuba Libre',
    ingredients: ['rum', 'lime', 'cola'],
    strength: 1,
    signature: false,
    nonalcoholic: false,
  },
  {
    name: 'The St. Germain Cocktail',
    ingredients: ['St. Germain', 'champagne', 'club soda'],
    strength: 1,
    signature: false,
    nonalcoholic: false,
  },
  {
    name: 'Trinidad',
    ingredients: ['rum', 'cola', 'angostura bitters'],
    strength: 1,
    signature: false,
    nonalcoholic: false,
  },
  {
    name: 'Rome with a View',
    ingredients: [
      'campari',
      'dry vermouth',
      'club soda',
      'lime',
      'simple syrup',
    ],
    strength: 1,
    signature: false,
    nonalcoholic: false,
  },
  {
    name: 'Bitter Intentions',
    ingredients: [
      'campari',
      'dry vermouth',
      'club soda',
      'lemon',
      'simple syrup',
    ],
    strength: 1,
    signature: false,
    nonalcoholic: false,
  },
  {
    name: 'Gin Fizz',
    ingredients: ['gin', 'lemon', 'club soda', 'simple syrup'],
    strength: 1,
    signature: false,
    nonalcoholic: false,
  },
  {
    name: 'Tom Collins',
    ingredients: [
      'gin',
      'simple syrup',
      'lemon',
      'club soda',
      'angostura bitters',
    ],
    strength: 1,
    signature: false,
    nonalcoholic: false,
  },
  {
    name: 'Lime Rickey',
    ingredients: ['lime', 'simple syrup', 'angostura bitters', 'club soda'],
    strength: 1,
    signature: false,
    nonalcoholic: false,
  },
  {
    name: 'Pink Gin',
    ingredients: ['gin', 'angostura bitters'],
    strength: 4,
    signature: false,
    nonalcoholic: false,
  },
  {
    name: 'Dry Martini',
    ingredients: ['gin', 'dry vermouth'],
    strength: 4,
    signature: false,
    nonalcoholic: false,
  },
  {
    name: 'Extra-dry Martini',
    ingredients: ['gin', 'dry vermouth'],
    strength: 4,
    signature: false,
    nonalcoholic: false,
  },
  {
    name: 'West Indian Cocktail',
    ingredients: ['gin', 'angostura bitters', 'lemon', 'sugar'],
    strength: 4,
    signature: false,
    nonalcoholic: false,
  },
  {
    name: 'Vesper',
    ingredients: ['gin', 'vodka', 'lillet blanc'],
    strength: 4,
    signature: false,
    nonalcoholic: false,
  },
  {
    name: 'Vodkatini',
    ingredients: ['vodka', 'dry vermouth'],
    strength: 4,
    signature: false,
    nonalcoholic: false,
  },
];
