// @flow

import type { Cocktail } from './Types';

export const cocktails: $ReadOnlyArray<Cocktail> = [
  {
    name: 'Coffee',
    ingredients: [],
    strength: 0,
    signature: false,
    nonalcoholic: true,
  },
  {
    name: 'Tea',
    ingredients: [],
    strength: 0,
    signature: false,
    nonalcoholic: true,
  },
  {
    name: 'Hot Tang',
    ingredients: [],
    strength: 0,
    signature: false,
    nonalcoholic: true,
  },
  {
    name: 'Hot Cocoa',
    ingredients: [],
    strength: 0,
    signature: false,
    nonalcoholic: true,
  },
  {
    name: 'Coca-Cola',
    ingredients: [],
    strength: 0,
    signature: false,
    nonalcoholic: true,
  },
  {
    name: 'Fever-tree Elderflower Tonic',
    ingredients: [],
    strength: 0,
    signature: false,
    nonalcoholic: true,
  },
  {
    name: 'Fever-tree Indian Tonic',
    ingredients: [],
    strength: 0,
    signature: false,
    nonalcoholic: true,
  },
  {
    name: 'Fever-tree Blood Orange Soda',
    ingredients: [],
    strength: 0,
    signature: false,
    nonalcoholic: true,
  },
  {
    name: 'Fever-tree Lemonade',
    ingredients: [],
    strength: 0,
    signature: false,
    nonalcoholic: true,
  },
  {
    name: 'Sparkling water',
    ingredients: [],
    strength: 0,
    signature: false,
    nonalcoholic: true,
  },
  {
    name: 'Negroni',
    ingredients: ['gin', 'sweet vermouth', 'campari'],
    strength: 3,
    signature: true,
    nonalcoholic: false,
  },
  {
    name: 'Queen Elizabeth',
    ingredients: ['rum', 'lime', 'grenadine'],
    strength: 3,
    signature: true,
    nonalcoholic: false,
  },
  {
    name: 'Long Island Iced Tea',
    ingredients: [
      'gin',
      'tequila',
      'vodka',
      'rum',
      'Cointreau',
      'simple syrup',
      'lemon',
      'cola',
    ],
    strength: 3,
    signature: true,
    nonalcoholic: false,
  },
  {
    name: 'Ward Eight',
    ingredients: ['whiskey', 'simple syrup', 'lemon', 'grenadine'],
    strength: 2,
    signature: true,
    nonalcoholic: false,
  },
  {
    name: 'Mark Twain Cocktail',
    ingredients: ['whiskey', 'lemon', 'simple syrup', 'bitters'],
    strength: 2,
    signature: true,
    nonalcoholic: false,
  },
  {
    name: 'Whiskey sour',
    ingredients: ['whiskey', 'lemon', 'simple syrup'],
    strength: 2,
    signature: true,
    nonalcoholic: false,
  },
  {
    name: 'The LJ 75',
    ingredients: ['gin', 'champagne', 'lemon', 'elderflower liqueur'],
    strength: 2,
    signature: true,
    nonalcoholic: false,
  },
  {
    name: 'Gin Daisy',
    ingredients: ['gin', 'lemon', 'grenadine', 'simple syrup', 'club soda'],
    strength: 2,
    signature: true,
    nonalcoholic: false,
  },
  {
    name: 'Boulevard',
    ingredients: ['whiskey', 'Cointreau', 'dry vermouth'],
    strength: 3,
    signature: false,
    nonalcoholic: false,
    recipe: { whiskey: 4, Cointreau: 1, 'dry vermouth': 1 },
  },
  {
    name: 'Box Car',
    ingredients: ['gin', 'Cointreau', 'lime', 'grenadine'],
    strength: 3,
    signature: false,
    nonalcoholic: false,
    recipe: { gin: 3, Cointreau: 1, lime: 1.5, grenadine: 0.5 },
  },
  {
    name: 'Rob Roy',
    ingredients: ['whiskey', 'sweet vermouth', 'bitters'],
    strength: 3,
    signature: false,
    nonalcoholic: false,
  },
  {
    name: 'Old Pal',
    ingredients: ['whiskey', 'dry vermouth', 'campari'],
    strength: 3,
    signature: false,
    nonalcoholic: false,
  },
  {
    name: 'Atta Boy',
    ingredients: ['gin', 'dry vermouth', 'grenadine'],
    strength: 3,
    signature: false,
    nonalcoholic: false,
    recipe: { gin: 2, 'dry vermouth': 1, grenadine: 0.5 },
  },
  {
    name: 'Aviation',
    ingredients: ['gin', 'maraschino', 'lemon'],
    strength: 3,
    signature: false,
    nonalcoholic: false,
    recipe: { gin: 3, maraschino: 1, lemon: 1 },
  },
  {
    name: 'Boulevardier',
    ingredients: ['whiskey', 'sweet vermouth', 'campari'],
    strength: 3,
    signature: false,
    nonalcoholic: false,
    recipe: { whiskey: 1, 'sweet vermouth': 1, campari: 1 },
  },
  {
    name: 'Manhattan',
    ingredients: ['whiskey', 'sweet vermouth', 'bitters'],
    strength: 3,
    signature: false,
    nonalcoholic: false,
  },
  {
    name: 'El Presidente',
    ingredients: ['rum', 'dry vermouth', 'Cointreau', 'grenadine'],
    strength: 3,
    signature: false,
    nonalcoholic: false,
  },
  {
    name: 'Rum Sunset',
    ingredients: ['rum', 'lime', 'grenadine'],
    strength: 3,
    signature: false,
    nonalcoholic: false,
    recipe: { rum: 4.5, lime: 2, grenadine: 1 },
  },
  {
    name: 'Crimson Breeze',
    ingredients: ['rum', 'dry vermouth', 'lemon', 'simple syrup', 'grenadine'],
    strength: 2,
    signature: true,
    nonalcoholic: false,
    recipe: {
      rum: 3,
      'dry vermouth': 1,
      lemon: 1,
      'simple syrup': 1,
      grenadine: 0.5,
    },
  },
  {
    name: 'Island Martini',
    ingredients: ['rum', 'gin', 'lime', 'grenadine'],
    strength: 4,
    signature: true,
    nonalcoholic: false,
    recipe: { rum: 4, gin: 2, lime: 1, grenadine: 0.5 },
  },
  {
    name: 'Kamikaze',
    ingredients: ['vodka', 'Cointreau', 'lime'],
    strength: 3,
    signature: false,
    nonalcoholic: false,
  },
  {
    name: 'Black Russian',
    ingredients: ['vodka', 'coffee liqueur'],
    strength: 3,
    signature: false,
    nonalcoholic: false,
    recipe: { vodka: 2, 'coffee liqueur': 1 },
  },
  {
    name: 'Brain Damage',
    ingredients: ['whiskey', 'coffee liqueur', 'grenadine'],
    strength: 3,
    signature: false,
    nonalcoholic: false,
    recipe: { whiskey: 2, 'coffee liqueur': 1, grenadine: 0.5 },
  },
  {
    name: 'Brave Bull',
    ingredients: ['tequila', 'coffee liqueur'],
    strength: 3,
    signature: false,
    nonalcoholic: false,
    recipe: { tequila: 1, 'coffee liqueur': 1 },
  },
  {
    name: 'Bloodhound',
    ingredients: ['dry vermouth', 'sweet vermouth', 'gin'],
    strength: 3,
    signature: false,
    nonalcoholic: false,
    recipe: { 'dry vermouth': 1, 'sweet vermouth': 1, gin: 4 },
  },
  {
    name: 'Campari Fizz',
    ingredients: ['campari', 'champagne'],
    strength: 2,
    signature: false,
    nonalcoholic: false,
    recipe: { campari: 1, champagne: 4 },
  },
  {
    name: 'Grey Russian',
    ingredients: ['vodka', 'coffee liqueur', 'amarula', 'whiskey'],
    strength: 3,
    signature: false,
    nonalcoholic: false,
    recipe: { vodka: 1, 'coffee liqueur': 1, amarula: 1, whiskey: 0.5 },
  },
  {
    name: 'Blenton',
    ingredients: ['gin', 'dry vermouth', 'bitters'],
    strength: 3,
    signature: false,
    nonalcoholic: false,
  },
  {
    name: "Devil's Torch",
    ingredients: ['vodka', 'dry vermouth', 'grenadine'],
    strength: 3,
    signature: false,
    nonalcoholic: false,
  },
  {
    name: 'Mudslide Shot',
    ingredients: ['vodka', 'Irish cream liqueur', 'coffee liqueur'],
    strength: 3,
    signature: false,
    nonalcoholic: false,
  },
  {
    name: 'Bicicletta',
    ingredients: ['campari', 'white wine', 'club soda'],
    strength: 1,
    signature: false,
    nonalcoholic: false,
    recipe: { campari: 1, 'white wine': 2, 'club soda': 1 },
  },
  {
    name: 'Bijou',
    ingredients: ['gin', 'Cointreau', 'dry vermouth', 'orange bitters'],
    strength: 3,
    signature: false,
    nonalcoholic: false,
    recipe: {
      gin: 2,
      Cointreau: 1,
      'dry vermouth': 1,
      'orange bitters': 0.5,
    },
  },
  {
    name: 'Gin and It',
    ingredients: ['gin', 'sweet vermouth', 'bitters'],
    strength: 3,
    signature: false,
    nonalcoholic: false,
  },
  {
    name: 'The Vampire',
    ingredients: ['gin', 'dry vermouth', 'lime'],
    strength: 3,
    signature: false,
    nonalcoholic: false,
  },
  {
    name: 'White Lady',
    ingredients: ['gin', 'Cointreau', 'lemon'],
    strength: 3,
    signature: false,
    nonalcoholic: false,
  },
  {
    name: 'Gin Sour',
    ingredients: ['gin', 'lemon', 'simple syrup'],
    strength: 3,
    signature: false,
    nonalcoholic: false,
  },
  {
    name: 'Royal Romance',
    ingredients: ['gin', 'Cointreau', 'grenadine'],
    strength: 3,
    signature: false,
    nonalcoholic: false,
  },
  {
    name: 'Upside-down martini',
    ingredients: ['dry vermouth', 'gin'],
    strength: 3,
    signature: false,
    nonalcoholic: false,
  },
  {
    name: "Devil's Own",
    ingredients: ['gin', 'dry vermouth', 'Cointreau', 'bitters'],
    strength: 3,
    signature: false,
    nonalcoholic: false,
  },
  {
    name: 'Gibson',
    ingredients: ['gin', 'dry vermouth'],
    strength: 3,
    signature: false,
    nonalcoholic: false,
  },
  {
    name: 'Margarita',
    ingredients: ['tequila', 'Cointreau', 'lime'],
    strength: 3,
    signature: false,
    nonalcoholic: false,
  },
  {
    name: 'Mexican Firing squad',
    ingredients: ['tequila', 'lime', 'grenadine', 'bitters'],
    strength: 3,
    signature: false,
    nonalcoholic: false,
  },
  {
    name: 'B52',
    ingredients: ['Cointreau', 'coffee liqueur', 'Irish cream liqueur'],
    strength: 3,
    signature: false,
    nonalcoholic: false,
  },
  {
    name: 'Gimlet',
    ingredients: ['gin', 'lime', 'simple syrup'],
    strength: 2,
    signature: false,
    nonalcoholic: false,
  },
  {
    name: 'Fitzgerald',
    ingredients: ['gin', 'lemon', 'simple syrup', 'bitters'],
    strength: 2,
    signature: false,
    nonalcoholic: false,
  },
  {
    name: 'Gin Rickey',
    ingredients: ['gin', 'lime', 'simple syrup', 'club soda'],
    strength: 2,
    signature: false,
    nonalcoholic: false,
  },
  {
    name: 'Bitter French',
    ingredients: ['gin', 'campari', 'lemon', 'simple syrup', 'champagne'],
    strength: 2,
    signature: false,
    nonalcoholic: false,
    recipe: { gin: 4, campari: 1, lemon: 2, 'simple syrup': 2, champagne: 1 },
  },
  {
    name: 'French 75',
    ingredients: ['gin', 'champagne', 'lemon', 'simple syrup'],
    strength: 2,
    signature: false,
    nonalcoholic: false,
  },
  {
    name: 'American Flyer',
    ingredients: ['champagne', 'rum', 'lime', 'sugar'],
    strength: 2,
    signature: false,
    nonalcoholic: false,
  },
  {
    name: 'Daiquiri',
    ingredients: ['rum', 'lime', 'simple syrup'],
    strength: 2,
    signature: false,
    nonalcoholic: false,
  },
  {
    name: 'Tipperary',
    ingredients: ['whiskey', 'sweet vermouth'],
    strength: 2,
    signature: false,
    nonalcoholic: false,
  },
  {
    name: 'Americano',
    ingredients: ['campari', 'sweet vermouth', 'club soda'],
    strength: 2,
    signature: false,
    nonalcoholic: false,
  },
  {
    name: 'Affinity',
    ingredients: ['sweet vermouth', 'dry vermouth', 'whiskey', 'bitters'],
    strength: 3,
    signature: false,
    nonalcoholic: false,
  },
  {
    name: 'Allen Special',
    ingredients: ['gin', 'maraschino', 'lemon'],
    strength: 3,
    signature: false,
    nonalcoholic: false,
  },
  {
    name: 'Aperol Fizz',
    ingredients: ['champagne', 'aperol'],
    strength: 1,
    signature: false,
    nonalcoholic: false,
    recipe: { aperol: 1, champagne: 3 },
  },
  {
    name: 'Aperol Spritz',
    ingredients: ['champagne', 'aperol', 'club soda'],
    strength: 1,
    signature: false,
    nonalcoholic: false,
    recipe: { aperol: 1, champagne: 2, 'club soda': 1 },
  },
  {
    name: 'Addington Cocktail',
    ingredients: ['dry vermouth', 'sweet vermouth', 'club soda'],
    strength: 2,
    signature: false,
    nonalcoholic: false,
  },
  {
    name: 'Cuba Libre',
    ingredients: ['rum', 'lime', 'cola'],
    strength: 1,
    signature: false,
    nonalcoholic: false,
  },
  {
    name: 'The St. Germain Cocktail',
    ingredients: ['St. Germain', 'champagne', 'club soda'],
    strength: 1,
    signature: false,
    nonalcoholic: false,
  },
  {
    name: 'Trinidad',
    ingredients: ['rum', 'cola', 'bitters'],
    strength: 1,
    signature: false,
    nonalcoholic: false,
  },
  {
    name: 'Rome with a View',
    ingredients: [
      'campari',
      'dry vermouth',
      'club soda',
      'lime',
      'simple syrup',
    ],
    strength: 1,
    signature: false,
    nonalcoholic: false,
  },
  {
    name: 'Bitter Intentions',
    ingredients: [
      'campari',
      'dry vermouth',
      'club soda',
      'lemon',
      'simple syrup',
    ],
    strength: 1,
    signature: false,
    nonalcoholic: false,
    recipe: {
      campari: 4,
      'dry vermouth': 2,
      'club soda': 3,
      lemon: 1.5,
      'simple syrup': 1.5,
    },
  },
  {
    name: 'Gin Fizz',
    ingredients: ['gin', 'lemon', 'club soda', 'simple syrup'],
    strength: 1,
    signature: false,
    nonalcoholic: false,
  },
  {
    name: 'Tom Collins',
    ingredients: ['gin', 'simple syrup', 'lemon', 'club soda', 'bitters'],
    strength: 1,
    signature: false,
    nonalcoholic: false,
  },
  {
    name: 'Lime Rickey',
    ingredients: ['lime', 'simple syrup', 'bitters', 'club soda'],
    strength: 1,
    signature: false,
    nonalcoholic: false,
  },
  {
    name: 'Dry Martini',
    ingredients: ['gin', 'dry vermouth'],
    strength: 4,
    signature: false,
    nonalcoholic: false,
  },
  {
    name: 'West Indian Cocktail',
    ingredients: ['gin', 'bitters', 'lemon', 'sugar'],
    strength: 4,
    signature: false,
    nonalcoholic: false,
  },
  {
    name: 'Vesper',
    ingredients: ['gin', 'vodka', 'lillet blanc'],
    strength: 4,
    signature: false,
    nonalcoholic: false,
  },
  {
    name: 'Vodkatini',
    ingredients: ['vodka', 'dry vermouth'],
    strength: 4,
    signature: false,
    nonalcoholic: false,
  },
];
